### ISSUE TITLE
no "energy" measurement?

### ISSUE THREAD

**Issue by Zakraket** [biemond/solaredge.modbus#19]
I just switched from Diederik's Bakker "Zonnepanelen" app to your SolarEdge app for my SE1500m 4x300w panel installation. Works fine, however I'm not seeing a "daily generated energy" anywhere.
It's available in the other app so I'm assuming the convertor has it available?

![Screenshot_5](https://user-images.githubusercontent.com/71003462/199437092-fc898534-916e-4724-9226-7930af6e78bf.jpg)

![Screenshot_4](https://user-images.githubusercontent.com/71003462/199436933-0a163c35-a43c-45ab-a211-6124c781b607.jpg)

I see it mentioned on the apppage in the reviews

**Comment by biemond** [comment]
awesome timing,  check this one https://homey.app/nl-nl/app/solaredge.modbus/SolarEdge/test/

**Comment by Zakraket** [comment]
Great! Works like a charm

One comment: it reports 0kWh now (just updated), while my app reports 0,9kWh for today. I don't know if the invertor "holds" the total day value by itself (so maybe it's not possible to get this from the invertor). This will of course be fixed tomorrow when it starts again at 0

**Comment by biemond** [comment]
indeed, I have to store now when it is empty and on 0:01 it will use the new value and caculate from that moment

**Comment by biemond** [comment]
also this calculated based on the export value. there is some diff with the app.  maybe solaredge has a better info then me
