### ISSUE TITLE
No data from inverter

### ISSUE THREAD

**Issue by djvanas** [biemond/solaredge.modbus#20]
Hi, since a couple of days no data is comming from the inverter. I have removed the app and reinstalled but it didn't help. Can you please check/forward me the diag report (6e52cc1c-89d6-4ea8-b2bc-f18e7e330b74)

**Comment by biemond** [comment]
Hey ,

I saw connection refused.  please check your ip and port plus use a LAN connection.  maybe you got a firmware update .

**Comment by djvanas** [comment]
Tnx for the prompt reply, newbie error. 

For other people facing same issue; default port is 502 for SolarEdge inverters with LCD screen.

Tnx

**Comment by biemond** [comment]
yep, ok yes.
