### ISSUE TITLE
Dynamic Commands

### ISSUE THREAD

**Issue by WillemsF** [biemond/solaredge.modbus#23]
Hey,
I am testing the possibilities to switch to a dynamic energy contract.
During testing it appears that all modes work except mode 3 => charge from PV+AC
I can't charge the battery from the grid...
In the manual I read to set the solaredge ac_charge policy to "1".
Could that be the reason why it doesn't work?

![image](https://user-images.githubusercontent.com/112898734/202923967-a2c44db5-5043-487c-92a0-77afad58edaf.png)

**Comment by biemond** [comment]
Hey,

I think I had the same in the beginning , I remember that I did this from the menu and my battery was tested. After that I was allowed to do this. 

but let me check again.

**Comment by biemond** [comment]
at least it still works.

![Screenshot 2022-11-21 at 09 48 55](https://user-images.githubusercontent.com/1085004/203006041-6ba97ae6-9295-421a-9eef-4bf8713900bc.png)

**Comment by WillemsF** [comment]
solved, activating a profile charge from AC for a while did indeed do the trick.
Is this a permanent condition?
![image](https://user-images.githubusercontent.com/112898734/203136433-9f69ca2a-c02e-443e-b757-d9e062f058b3.png)
NO LIMIT
![image](https://user-images.githubusercontent.com/112898734/203136566-22141128-a1b5-466c-a6f6-4fedf2c370ec.png)
1000W CHARGE LIMIT.

Perfect!!

**Comment by biemond** [comment]
nice, in my case it was testing batt 1st. 

Also when batt is low , what also will happen it will slow charge from 8 / 9 until 10% before going full charge.

**Comment by biemond** [comment]
yeah, if you switch to hour prices , sometimes it is free .  hour by the power app. you maybe can automate thus

**Comment by WillemsF** [comment]
that's the idea... getting a contract now will be a bigger challenge.
to automate this day ahead prices I have already found the app on Homey
![image](https://user-images.githubusercontent.com/112898734/203140394-9d09bd33-fa46-41ad-a73a-17c78913d678.png)

**Comment by biemond** [comment]
yep, 1 day before you can already  know the hours.
