### ISSUE TITLE
Missing variables

### ISSUE THREAD

**Issue by jowamedia** [biemond/solaredge.modbus#3]
Hi, 
thanks a lot for your app.
It use to work perfectly, but since several days, it miss some variables, like : 
- Power Export
- Power Import
- Consumption

I use these last variables to manage the car charger.
I had to reinstall the device, has it lost the connexion. The port on my Solaredge is 502 (not 1502 as default in the app).
Would it be possible to have theses variables again ?

Thanks a lot in advance.
Best,
Joel

**Comment by biemond** [comment]
Hey, 

let me check this consumption.  I think I need  to calculate this.
I think latetly make sure you don't use wifi, they disabled modbus tcp over wifi , only over lan.


<img width="351" alt="Screen Shot 2022-04-04 at 22 31 11" src="https://user-images.githubusercontent.com/1085004/161627017-7b4ae96d-88d8-4d65-a6f7-16001fd693b5.png">


<img width="375" alt="Screen Shot 2022-04-04 at 22 27 15" src="https://user-images.githubusercontent.com/1085004/161626696-1ddfca19-e353-4dd3-84f3-25eb2efefd02.png">

<img width="1301" alt="Screen Shot 2022-04-04 at 22 28 40" src="https://user-images.githubusercontent.com/1085004/161626712-6e706cac-f200-4270-889f-8de7d957f83a.png">

**Comment by jowamedia** [comment]
Thanks looks great.
(I use LAN, not wifi).

For consumption, if you look on the app, it shows the power consumption. You may have an address for that in the modbus !?

**Comment by biemond** [comment]
It is calculated. but I will add it, I got all the information.

**Comment by biemond** [comment]
Hey , can you check this release. see if it works for you

https://homey.app/a/solaredge.modbus/test/

**Comment by jowamedia** [comment]
Hey, I do have the v.2.0.13. When I click on the link ending with test, the
URL is redirecting to the normal one.
How to install this test version ?

Le dim. 10 avr. 2022 à 11:52, Edwin Biemond ***@***.***> a
écrit :

**Comment by biemond** [comment]
yes , good. homey already approved it,  does it work for you?

**Comment by jowamedia** [comment]
Ok, good.
But I don't have additional values :
![IMG_ECD60003DABC-1](https://user-images.githubusercontent.com/8236760/165256282-a2c6b135-cc28-45ed-9ce7-55c24c7d3b12.jpeg)

nor in flow.

Shell I reinstall the converter to get them ?

**Comment by biemond** [comment]
can you try the battery invertor device instead.  I am checking it all, no worries when you don't have a battery. 
so you have meters installed without a battery?

**Comment by jowamedia** [comment]
yes exactly, I don't have battery. I do have the Solaredge SE9k.

**Comment by biemond** [comment]
ok I am checking it and everything is optional.  so batt inverter device should work for you then
can you try that 1

**Comment by jowamedia** [comment]
now I am getting the values and they are updated every few seconds. I will look at it a few days and check if everything works fine. 
Thanks for the dev ,-)
I appreciate.

**Comment by jowamedia** [comment]
Ok, good.
But I don't have additional values :
[image: IMG_ECD60003DABC-1.jpeg]
nor in flow.

Shell I reinstall the converter to get them ?


Le mar. 12 avr. 2022 à 20:33, Edwin Biemond ***@***.***> a
écrit :
