### ISSUE TITLE
Uitlezen Modbus TPC over VPN werkt niet

### ISSUE THREAD

**Issue by haandrw** [biemond/solaredge.modbus#32]
![Uploading 3A4B7D89-B6E9-4ED1-90D3-C534CC2FC805.jpeg…]()
Ik probeer via VPN een andere SolarEdge inverter uit te lezen. Met Modbus tools kan ik zien dat de verbinding werkt, echter in de Homey app krijg ik geen data. Als ik port forwarding gebruik (veel te gevaarlijk) lukt het wel om data te ontvangen. Ik begrijp niet waar dit fout gaat/waarom het niet werkt. Wellicht een blokkering in de software.

**Comment by biemond** [comment]
hey,

is je homey in een vlan of zo en mag het geen connectie opzetten naar je inverter over vpn. 
als port forwarding werkt dan zal waarschijnlijk op dat device het fout gaan en wordt geblokt.

Ik doe niks speciaal.  kun je een logger of sniffer aanzetten.  

Laatst nog homey over een vpn geconnect naar inverter in belgie.

**Comment by haandrw** [comment]
Nee Homey is gewoon in LAN, via zelfde connection point als waarmee ik wel via iPad en een Modbus app wel de data ontvang. Als het standaard wel zou moeten werken ga ik eens verder onderzoeken of ik een oorzaak kan vinden. Dank voor de snelle reactie.

**Comment by biemond** [comment]
kun je me een diagnostic rapport sturen.  misschien crashed de app.

**Comment by haandrw** [comment]
Ik heb nog geprobeerd om mijn eigen inverter (lokale connectie via LAN) te verwijderen om te testen of dat invloed heeft op de 2e remote (via VPN) inverter. Dit heeft niets opgeleverd, nog altijd geen gegevens van de inverter die via VPN is gekoppeld beschikbaar in Homey app.

**Comment by biemond** [comment]
ga het checken

**Comment by biemond** [comment]
```
Error: connect ETIMEDOUT [192.168.2.67:1502](http://192.168.2.67:1502/)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.168.2.67',
  port: 1502
}
```

**Comment by biemond** [comment]
ik denk dat de weg terug niet goed gaat en daarom krijg ik een timeout.

**Comment by biemond** [comment]
ik vermoed dat er een soort handshaking plaats vind.  Ik krijg geen connection refused.

**Comment by biemond** [comment]
ik gebruik https://github.com/biemond/solaredge.modbus/blob/main/package.json#L18
misschien keep alive kan het verschil maken 
```
   let modbusOptions = {
      'host': this.getSetting('address'),
      'port': this.getSetting('port'),
      'unitId': this.getSetting('id'),
      'timeout': 15,
      'autoReconnect': false,
      'logLabel' : 'solaredge Inverter',
      'logLevel': 'error',
      'logEnabled': true
    }    

    let socket = new net.Socket();
    var unitID = this.getSetting('id');
    let client = new Modbus.client.TCP(socket, unitID);
    socket.setKeepAlive(false);
    socket.connect(modbusOptions);
```

**Comment by biemond** [comment]
ben nu bezig een test versie te pushen maar daarna kan ik het aanpassen en een test versie voor je klaar zetten

**Comment by haandrw** [comment]
Oorzaak is denk ik gevonden… mijn site2site connection is down. Ik ga proberen die weer in de lucht te krijgen.

**Comment by haandrw** [comment]
Probleem was inderdaad netwerk gerelateerd. Nu dat is opgelost werkt het als een zonnetje!
![22C785AE-773E-4803-A0EC-ADFB917F58B0](https://user-images.githubusercontent.com/34268594/230857484-7ec2b89c-ef19-4a34-897f-536f1c19041f.jpeg)
