### ISSUE TITLE
No more data?

### ISSUE THREAD

**Issue by Xybertecnic** [biemond/solaredge.modbus#38]
Till this morning communication with my SE4000H HD Wave worked fine, but since a couple of hours I can't get any data anymore. I have deleted and re-added the inverter without issues, but still no data, any idea what might be the problem?

![2023-06-19_113924](https://github.com/biemond/solaredge.modbus/assets/131592989/300f65d5-60c6-497d-9013-de3b60793a8e)
![2023-06-19_114727](https://github.com/biemond/solaredge.modbus/assets/131592989/1794c509-b0f6-4844-87b8-e7bccc6cb2c8)

**Comment by biemond** [comment]
plus send me a diagnostic report. so I can see what is happening.

**Comment by biemond** [comment]
```
[Device:03623de3-d317-46dd-bc50-c0a4ea8f7957] 192.185.1.14
Error: connect ECONNREFUSED [192.185.1.14:1502](http://192.185.1.14:1502/)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.185.1.14',
  port: 1502
}
```

**Comment by biemond** [comment]
check mdns entry on your phone

**Comment by Xybertecnic** [comment]
> check mdns entry on your phone

die vind hem niet

**Comment by Xybertecnic** [comment]
I can see it in the solaredge app just fine

**Comment by biemond** [comment]
yes there was an update but it cannot connect to your inverter. so when ip is ok , it can be solaredge menu setting like port or modbus id. else you would see a stacktrace.

Or network issue.  also there should be no other app who connects to it and blocks homey.

**Comment by Xybertecnic** [comment]
well I don't know what happens with my Asus Router but I have problems with everything the last few days, before my P1 meter did not connect anymore, now the solaredge, but in the end even though I had set the IP of the SE fixed in my router, it still did not get it assigned, it was set to a completely different IP address. I had to go look into the inverter itself to find out. Everything works now again :-) Maybe next time buy another brand router...

**Comment by Xybertecnic** [comment]
Would you mind removing the message with all the mac details etc? Don't know if it is harmfull but better safe than sorry...

**Comment by biemond** [comment]
also had  this once on some p1 meter , I assign a fixed on mac address with dhcp but totally ignores it and does not connect.

probably some devices does not follow dhcp  or ehternet strictly or router is less strict.

**Comment by Xybertecnic** [comment]
in any case, thanks for your help

**Comment by biemond** [comment]
by the way do you see mdns entry now on your phome?

**Comment by Xybertecnic** [comment]
> by the way do you see mdns entry now on your phome?

no, not found, everything else is, but not the inverter
