### ISSUE TITLE
Omvormer geeft niks meer door

### ISSUE THREAD

**Issue by Geos3** [biemond/solaredge.modbus#41]
Goedenavond,

Ik heb helaas weer een probleempje met de app.

Hij geeft geen waardes meer door.

Heb de app verwijderd en opnieuw geïnstalleerd.

Maar hielp helaas niet.

Ik hoop op een oplossing.

Alvast top bedankt!

Groet Floris

**Comment by biemond** [comment]
Hey,

heb. je al gekeken of je ip adres is veranderd?  en kijk of je inverter een mdns/bonjour entry laat zien met ip, port en modbus id. je hebt hiervoor een android of iphone app.

anders zend even een diagnostic report . maar het is meestal altijd het ip adres of een soort firewall rule als het ooit heeft gewerkt,

groet Edwin

**Comment by Geos3** [comment]
9462757c-c59b-4e7c-b28a-0ced861944fd

**Comment by biemond** [comment]
yep, kan hem niet bereiken.

```
[Device:d630a1d7-37a6-4d8a-beb1-560738ccda73] 192.168.1.53
Error: connect EHOSTUNREACH [192.168.1.53:1502](http://192.168.1.53:1502/)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.1.53',
  port: 1502
}
Client closed
```

**Comment by Geos3** [comment]
Beste Edwin,

Idd. Je had gelijk ip adres is veranderd !!

Aangepast en het werkt.

Erg bedankt voor je snelle antwoord!!

Fijne avond 

Groet Floris

**Comment by biemond** [comment]
kun je eens kijken op je telefoon of laptop  of je die mdns entry kan zien

**Comment by Geos3** [comment]
Hoi Edwin,
Inmiddels opgelost !

Was ip nummer.

Erg bedankt voor jou snelle hulp!

Groet Floris

**Comment by Geos3** [comment]
Beste Edwin,

Erg bedankt voor jou snelle hulp!

Was ip adres die was veranderd..

Groet Floris


________________________________
