### ISSUE TITLE
function descriptions

### ISSUE THREAD

**Issue by kicksev** [biemond/solaredge.modbus#49]
I recently got a Solaredge inverter 10.5K 3-phase with a 9 KWh battery system and a dynamic energy contract. For this, I'm looking for a way to control the inverter, and to my great delight, I found this app for my Homey. Now, I'm looking for some information on what the provided functions do and the meaning of the different statuses. Probably, this info is available somewhere, but I can't find it. Can you give me a hint?

**Comment by biemond** [comment]
hey, yes please check the solaredge manuals but you can basically limit import (use batt more) , export (with negative prices)  . or charge / disacharge the battery to grid when prices are ok. 


[SolarEdge_StorEdge_Manual_V2.pdf](https://github.com/biemond/solaredge.modbus/files/12388068/SolarEdge_StorEdge_Manual_V2.pdf)

**Comment by biemond** [comment]
<img width="1203" alt="Screen Shot 2023-08-20 at 14 06 11" src="https://github.com/biemond/solaredge.modbus/assets/1085004/3700d9e4-11b1-4e94-8913-e5835b4b382b">
<img width="1178" alt="Screen Shot 2023-08-20 at 14 06 24" src="https://github.com/biemond/solaredge.modbus/assets/1085004/e5f1693b-acb9-4cc4-a097-8d4902aec0df">

**Comment by kicksev** [comment]
Thank you for your help.
