### ISSUE TITLE
No data from SolarEdge anymore

### ISSUE THREAD

**Issue by NIke13A** [biemond/solaredge.modbus#58]
Since 29 days Homey doesn't get data from SolarEdge inverter (w/o display) anymore. Before that it all worked fine.

The inverter got a new (static) IP, which I checked and entered in the app. Port 1502 and ID 1.

Any clues?

**Comment by NIke13A** [comment]
Problem solved. The electrician updated the firmware a month ago and set the invertor to default factory settings. Reactivating modbus did the trick. Sorry for bothering.

**Comment by biemond** [comment]
at least good he updated the firmware
